package main

import (
	"context"
	"log"
	"testing"

	"github.com/gin-gonic/gin"

	"versionary-api/pkg/email"
	"versionary-api/pkg/org"
	"versionary-api/pkg/token"
	"versionary-api/pkg/user"
)

var r = gin.New()
var userOrg org.Organization
var regularUser user.User
var regularToken string
var adminUser user.User
var adminToken string
var emailOne email.Email
var emailTwo email.Email

func TestMain(m *testing.M) {
	// Initialize the application for testing
	err := api.InitMock("dev")
	if err != nil {
		log.Fatal(err)
	}

	// TODO: Populate the database with test data
	generateUsers()
	generateEmails()

	// Initialize the gin router
	r.Use(gin.Recovery())
	gin.SetMode(gin.TestMode)
	gin.DisableConsoleColor()
	registerRoutes(r)

	// Run the tests
	m.Run()
}

func generateUsers() {
	ctx := context.Background()
	// Test Organization
	org, problems, err := api.OrgService.Create(ctx, org.Organization{
		Name:   "Versionary",
		Status: org.ENABLED,
	})
	if err != nil || len(problems) > 0 {
		log.Fatal(err)
	}
	userOrg = org

	// Regular API user (no special roles) and associated bearer token
	rUser, problems, err := api.UserService.Create(ctx, user.User{
		GivenName:  "Regular",
		FamilyName: "User",
		Email:      "info@versionary.net",
		OrgID:      userOrg.ID,
		OrgName:    userOrg.Name,
		Roles:      []string{"creator"},
		Status:     user.PENDING,
	})
	if err != nil || len(problems) > 0 {
		log.Fatal(err)
	}
	regularUser = rUser
	rToken, err := api.TokenService.Create(ctx, token.Token{
		UserID: rUser.ID,
		Email:  rUser.Email,
	})
	if err != nil {
		log.Fatal(err)
	}
	regularToken = rToken.ID

	// Admin API user (has admin role) and associated bearer token
	aUser, problems, err := api.UserService.Create(ctx, user.User{
		GivenName:  "Admin",
		FamilyName: "User",
		Email:      "admin@versionary.net",
		Roles:      []string{"admin"},
		OrgID:      userOrg.ID,
		OrgName:    userOrg.Name,
		Status:     user.ENABLED,
	})
	if err != nil || len(problems) > 0 {
		log.Fatal(err)
	}
	adminUser = aUser
	aToken, err := api.TokenService.Create(ctx, token.Token{
		UserID: aUser.ID,
		Email:  aUser.Email,
	})
	if err != nil {
		log.Fatal(err)
	}
	adminToken = aToken.ID
}

func generateEmails() {
	ctx := context.Background()
	// Test Emails no1
	email1, problems, err := api.EmailService.Create(ctx, email.Email{
		From: email.Identity{
			Name:    adminUser.FullName(),
			Address: adminUser.Email,
		},
		To: []email.Identity{
			{
				Name:    regularUser.FullName(),
				Address: regularUser.Email,
			},
		},
		Subject:  "Email from admin to regular user",
		BodyText: "This is the first email generated by the test suite.",
		Status:   email.UNSENT,
	})
	if err != nil || len(problems) > 0 {
		log.Fatal(err)
	}
	emailOne = email1

	// Test Emails no2
	email2, problems, err := api.EmailService.Create(ctx, email.Email{
		From: email.Identity{
			Name:    regularUser.FullName(),
			Address: regularUser.Email,
		},
		To: []email.Identity{
			{
				Name:    adminUser.FullName(),
				Address: adminUser.Email,
			},
		},
		Subject:  "Second generated email",
		BodyText: "This is the second email generated by the test suite.",
		Status:   email.UNSENT,
	})
	if err != nil || len(problems) > 0 {
		log.Fatal(err)
	}
	emailTwo = email2
}
